const Error = require("../utils/error");

const main = (req, res) => {
  res.json({ message: "Funcionando" });
};

const error = (req, res) => {
  throw new Error(404, "NÃ£o encontrado");
};

module.exports = { main, error };
